# Build NodeJS Express app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript?view=vsts
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install

- task: Npm@1
  displayName: 'npm run prod'
  inputs:
    command: custom
    customCommand: 'run prod'

- task: Npm@
  displayName: 'npm test'
  inputs:
    command: custom
    customCommand: 'test'
