version: '2.1'

services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./.docker/nginx.production.dockerfile
    ports:
      - 80:80
    links:
      - node:node
    networks:
      - isomorphic-react-boilerplate-network

  node:
    image: pjolayres/private:isomorphic-react-boilerplate
    environment:
      NODE_ENV: production
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - 3000:3000
    networks:
      - isomorphic-react-boilerplate-network

networks:
  isomorphic-react-boilerplate-network:
    driver: bridge
